config/routes.rb
Disco::Application.routes.draw do
  resources :chansons

  

end

app/models/chanson.rb
class Chanson < ActiveRecord::Base
end

app/models/chanteur.rb
class Chanteur < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chansons_controller.rb
class ChansonsController < ApplicationController
  before_action :set_chanson, only: [:show, :edit, :update, :destroy]

  # GET /chansons
  # GET /chansons.json
  def index
    @chansons = Chanson.all
  end

  # GET /chansons/1
  # GET /chansons/1.json
  def show
  end

  # GET /chansons/new
  def new
    @chanson = Chanson.new
  end

  # GET /chansons/1/edit
  def edit
  end

  # POST /chansons
  # POST /chansons.json
  def create
    @chanson = Chanson.new(chanson_params)

    respond_to do |format|
      if @chanson.save
        format.html { redirect_to @chanson, notice: 'Chanson was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chanson }
      else
        format.html { render action: 'new' }
        format.json { render json: @chanson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chansons/1
  # PATCH/PUT /chansons/1.json
  def update
    respond_to do |format|
      if @chanson.update(chanson_params)
        format.html { redirect_to @chanson, notice: 'Chanson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chanson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chansons/1
  # DELETE /chansons/1.json
  def destroy
    @chanson.destroy
    respond_to do |format|
      format.html { redirect_to chansons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chanson
      @chanson = Chanson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chanson_params
      params.require(:chanson).permit(:titre, :parole)
    end
end

app/controllers/chanteurs_controller.rb
class ChanteursController < ApplicationController
  before_action :set_chanteur, only: [:show, :edit, :update, :destroy]

  # GET /chanteurs
  # GET /chanteurs.json
  def index
    @chanteurs = Chanteur.all
  end

  # GET /chanteurs/1
  # GET /chanteurs/1.json
  def show
  end

  # GET /chanteurs/new
  def new
    @chanteur = Chanteur.new
  end

  # GET /chanteurs/1/edit
  def edit
  end

  # POST /chanteurs
  # POST /chanteurs.json
  def create
    @chanteur = Chanteur.new(chanteur_params)

    respond_to do |format|
      if @chanteur.save
        format.html { redirect_to @chanteur, notice: 'Chanteur was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chanteur }
      else
        format.html { render action: 'new' }
        format.json { render json: @chanteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chanteurs/1
  # PATCH/PUT /chanteurs/1.json
  def update
    respond_to do |format|
      if @chanteur.update(chanteur_params)
        format.html { redirect_to @chanteur, notice: 'Chanteur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chanteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chanteurs/1
  # DELETE /chanteurs/1.json
  def destroy
    @chanteur.destroy
    respond_to do |format|
      format.html { redirect_to chanteurs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chanteur
      @chanteur = Chanteur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chanteur_params
      params[:chanteur]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chansons_helper.rb
module ChansonsHelper
end

app/helpers/chanteurs_helper.rb
module ChanteursHelper
end

app/views/chansons/_form.html.erb
<%= form_for(@chanson) do |f| %>
  <% if @chanson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chanson.errors.count, "error") %> prohibited this chanson from being saved:</h2>

      <ul>
      <% @chanson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :parole %><br>
    <%= f.text_area :parole %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chansons/edit.html.erb
<h1>Editing chanson</h1>

<%= render 'form' %>

<%= link_to 'Show', @chanson %> |
<%= link_to 'Back', chansons_path %>

app/views/chansons/index.html.erb
<h1>Listing chansons</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Parole</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chansons.each do |chanson| %>
      <tr>
        <td><%= chanson.titre %></td>
        <td><%= chanson.parole %></td>
        <td><%= link_to 'Show', chanson %></td>
        <td><%= link_to 'Edit', edit_chanson_path(chanson) %></td>
        <td><%= link_to 'Destroy', chanson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chanson', new_chanson_path %>

app/views/chansons/new.html.erb
<h1>New chanson</h1>

<%= render 'form' %>

<%= link_to 'Back', chansons_path %>

app/views/chansons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @chanson.titre %>
</p>

<p>
  <strong>Parole:</strong>
  <%= @chanson.parole %>
</p>

<%= link_to 'Edit', edit_chanson_path(@chanson) %> |
<%= link_to 'Back', chansons_path %>

app/views/chanteurs/_form.html.erb
<%= form_for(@chanteur) do |f| %>
  <% if @chanteur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chanteur.errors.count, "error") %> prohibited this chanteur from being saved:</h2>

      <ul>
      <% @chanteur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chanteurs/edit.html.erb
<h1>Editing chanteur</h1>

<%= render 'form' %>

<%= link_to 'Show', @chanteur %> |
<%= link_to 'Back', chanteurs_path %>

app/views/chanteurs/index.html.erb
<h1>Listing chanteurs</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chanteurs.each do |chanteur| %>
      <tr>
        <td><%= link_to 'Show', chanteur %></td>
        <td><%= link_to 'Edit', edit_chanteur_path(chanteur) %></td>
        <td><%= link_to 'Destroy', chanteur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chanteur', new_chanteur_path %>

app/views/chanteurs/new.html.erb
<h1>New chanteur</h1>

<%= render 'form' %>

<%= link_to 'Back', chanteurs_path %>

app/views/chanteurs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chanteur_path(@chanteur) %> |
<%= link_to 'Back', chanteurs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Disco</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>